#!/bin/bash

# vérification du contexte général
verifier()
{
  if [ ! "$1" "$2" ] ; then
    echo "Erreur! $2 n'existe pas"
    exit 1
  fi
}

# Récupération du Makefile et création des liens spécifiques à ce tp05
makefile_original="/users/info/pub/s4/M4102C/data/Makefile"
verifier -f "$makefile_original"

origine="../commun"

for rep in client serveur
do
  (
  verifier -d "$rep"
  cd "$rep"
  ln -si "$makefile_original" .
  ln -si "$origine/"* .
  )
done
