#!/bin/bash
echo "Utilisation des \"\""
echo "Prix du double slash \\ : $expensive"
echo ""
echo "Utilisation des '' "
echo 'Prix du double slash \\ : $expensive'
echo ""
echo "Utilisation des \`\`"
echo `Prix du double slash \\ : $expensive`
